# -*- coding: utf-8 -*-
"""変数を使って四則演算をしよう.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/176uAk-8BeDZQWLEE_2z0eqOKntOVKep6
"""

#台形の寸法
s_ue = 10 #上辺寸法
s_sita = 20 #下辺寸法
s_takasa = 5 #高さ

#台形の面積計算
menseki = ((s_ue+s_sita)*s_takasa)/2
print(str(menseki)+"cm²")